### ISSUE TITLE
주제 선정하기

### ISSUE THREAD

**Issue by changhyeon12333** [changhyeon12333/Creation#1]
주제 선정에 관하여 의견 있으면 적어주세요.

**Comment by changhyeon12333** [comment]
시각장애인이나 다른 사람의 감정을 이해하는데 불편함이 있는 분들을 위해
카메라를 통하여 상대방의 표정을 모니터링 해 감정을 파악하는데 도움을 주는 프로그램

**Comment by changhyeon12333** [comment]
뉴스기사 모니터링 - 기업들의 뉴스를 긍정이나 부정적인 기사인지 판단하여 향후 기업동향을 얕게 파악하는 프로그램

**Comment by dtp06077** [comment]
독거 노인이나 자취 창년들의 고독사 및 사고사 방지를 위한 생체감지 모니터링 프로그램

**Comment by dtp06077** [comment]
모니터링을 통해 사용자의 오타패턴을 분석해서 자동으로 오타를 고쳐주는 어플

**Comment by changhyeon12333** [comment]
브레이크 모니터링
요즘 사건이 많은 급발진사고인정을 위한 시스템
브레이크를 밟은 사실을 기록하여 급발진 의심 사고가 발생할 시 
개인이 명확하게 확인해 볼 수 있음. (운전미숙등의 이유로 악셀을 밟고 급발진이라고 주장하는 사실이 꽤 있음)

**Comment by leejuhyub** [comment]
태풍 감지 모니터링
여름철 우리나라뿐만 아니라 다른나라에서도 많은 인명피해 및 피해를 주는 태풍을 미리 감지할 수 있게 해주는 시스템
태풍의 원인은 북태평양수온과 기압에 있는데 수온을 계속 모니터링하면서 태풍의 규모를 예측하고
극동 무역풍과 편서풍 또한 모니터링하면서 태풍의 움직임을 예측해준다.
