### ISSUE TITLE
어플리케이션 부가적인 서비스

### ISSUE THREAD

**Issue by dtp06077** [changhyeon12333/Creation#2]
운전자를 위한 네비게이션 서비스 제공

**Comment by dtp06077** [comment]
졸음운전 예방을 위한 경고 알람 서비스 제공

**Comment by changhyeon12333** [comment]
블루투스를 통한 모바일 연동이아닌
직접적인 모바일 연결로 데이터를 보내면서 충전까지 할 수 있게 한다

**Comment by leejuhyub** [comment]
액셀과 브레이크를 밟는 습관을 통한 연비 측정 서비스
