### ISSUE TITLE
사용자들의 데이터를 수집 및 분석하여 제공할 수 있는 정보

### ISSUE THREAD

**Issue by dtp06077** [changhyeon12333/Creation#3]
사용자가 졸음운전 사고를 냈을 경우, 사고 당시의 차량 내부의 온도와 습도 데이터를 수집 및 분석하여 어떤 환경에서 졸음운전 사고가 잘 일어나는지 정보 제공

**Comment by changhyeon12333** [comment]
에어백 부분을 탐지하여
큰 사고가 났을 때 주변에 사람이 없을 경우 차량 사고를 감지해서
근처 119나 경찰에게 신고를 해주는 시스템

**Comment by leejuhyub** [comment]
사용자들이 급 브레이크를 밟는 구간또는 지점을 GPS 상을 통해 파악한 후 사용자가 그 지점을 지나갈때 알림
