### ISSUE TITLE
DB구성 SQL작성

### ISSUE THREAD

**Issue by changhyeon12333** [changhyeon12333/Creation#36]

**Comment by dtp06077** [comment]
f로그인 테이블
CREATE TABLE `USER`(
userID VARCHAR(50) NOT NULL,
userPassword VARCHAR(50) NOT NULL,
userCarnum VARCHAR(50) NOT NULL,
PRIMARY KEY(userID)
);

**Comment by changhyeon12333** [comment]
php 작성 하겠습니다
