### ISSUE TITLE
개선사항 및 미흡한점 

### ISSUE THREAD

**Issue by changhyeon12333** [changhyeon12333/Creation#61]
프로젝트를 마치며 필요한 개선사항과 미흡한점에 대해 말씀해주십쇼

**Comment by changhyeon12333** [comment]
기본적인 기능만 구현하도록 했기 때문에 
Android UI가 실제 사용자가 보기 불편하고 보기 불편합니다 그리고 실측정시 초음파 센서가 일자로 배치되어 음파가 겹치는 상황이 생겨 어려움이 많아 센서 선정에서 미흡했던거 같습니다.

**Comment by dtp06077** [comment]
모의 주행 해본 결과 운전자 입장에서 모듈 설치가 어렵고 선이 복잡하였음

**Comment by changhyeon12333** [comment]
그리고 개발계획이 평탄히 이루어지지 않아 계획했던 서비스를 모두 넣진 못했습니다. 19일 평가가 마친 후 UI와 추가서비스에 대해 같이 진행해 봅시다 ㅎㅎ
